version: '3'
services:
  react:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - NODE_ENV=development
    volumes:
     - ./:/usr/src/app
    command: sh -c "cd workplace && yarn start"
    ports:
     - "3000:3000"
    tty: true
